### ISSUE TITLE
Warning: React has detected a change in the order of Hooks called by WrapRoot.

### ISSUE THREAD

**Issue by cryptolokimax** [PsychedMagnet/gatsby-theme-localization#1]
Hello,

First of all, thank you for the plugin - it's exactly what I was looking for. However it seems to have a problem with rendering. Console displays the following error:

```
Warning: React has detected a change in the order of Hooks called by WrapRoot. This will lead to bugs and errors if not fixed. For more information, read the Rules of Hooks: https://fb.me/rules-of-hooks

   Previous render            Next render
   ------------------------------------------------------
1. useState                   useContext
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    in WrapRoot (created by LocationProvider)
    in LocationProvider (created by Context.Consumer)
    in Location (created by WithLocationComponent)
    in WithLocationComponent
    in Suspense
    in _default (at app.js:67)
```

Which affects the build, I beleive, as after rendered page is loaded, it flickers to translation variables, which are replaced by translation in a fraction of a second.

Do you have any idea of what it can be?

**Comment by PsychedMagnet** [comment]
Hi!
First of all, thank you for using my plugin and leaving feedback!

About the order of hooks issue, I get the error too. However, I am not sure why that happens as all the hooks are rendered the same way each time, and I haven't used neither `useState` nor `useContext` in WrapRoot. This leads me to think that something is internally using those to cause the problem. I will look into it immediately! Thank you for reporting!

About the flicker problem, did you set `useSuspense` and `wait` options in i18next to `true`? Refer to the [example config here](https://github.com/PsychedMagnet/gatsby-theme-localization/blob/77d5bf447d97a2496025345ebb3b04356ab24d81/example/gatsby-config.js#L13-L20). Does this solve at least the flicker issue for you?

**Comment by PsychedMagnet** [comment]
I think I managed to pinpoint the problem - `useTranslation` from `react-i18next` calls `useContext` conditionally. I opened an issue and made a PR. As soon as it is fixed, I will update `react-i18next` in this plugin and the issue should be resolved! :)

You can track the issue [here ](https://github.com/i18next/react-i18next/issues/934) if you are interested.

**Comment by PsychedMagnet** [comment]
Turns out there was also a goof up on my part. I fixed it and the issue should be gone now, but I will still update the package when/if my PR is merged.

Update to the latest version and tell me if the issue persists :)

**Comment by cryptolokimax** [comment]
Thank you for fast response! Yes, the issue was fixed for me, thank you! Now it's officially the best and easiest localisation plugin for gatsby! :)

**Comment by PsychedMagnet** [comment]
Thank you, I am glad you find it useful :)

I will be closing the issue now, if you have any other problems or feature suggestions, don't hesitate to open another issue!
